version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: product_db
      MYSQL_USER: springuser
      MYSQL_PASSWORD: password
    ports:
      - "3310:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin-container
    restart: always
    ports:
      - "9411:9411"
    deploy:
      update_config:
        order: start-first  # Ensures smooth updates during deployment

  redis:
    image: redis:latest
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  redis-data:
